print('=======DESAFIO_04==========')
n = input('Digite algo:')
print('O tipo primitivo desse valor é',type(n))
print('Só tem espacos?',n.isspace())
print('É um numero',n.isnumeric())
print('É alfabetico?',n.isalpha())
print('Está em em maiúsculas?',n.isupper())
print('Está em minusculas?',n.islower())
print('Está capitalizada?',n.istitle())

